# Generated by Django 2.2.7 on 2020-03-23 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=5, validators=[django.core.validators.EmailValidator()])),
                ('comp_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('comp_code', models.CharField(max_length=254)),
                ('comp_mobile', models.CharField(max_length=10)),
                ('comp_address', models.TextField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=22)),
                ('orgEmail', models.EmailField(max_length=25)),
                ('orgContact', models.IntegerField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
