# Generated by Django 2.2.7 on 2020-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_name',
            field=models.CharField(max_length=50),
        ),
    ]
