# Generated by Django 2.2.7 on 2020-03-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=22)),
                ('father_name', models.CharField(max_length=22)),
                ('dob', models.DateField(max_length=22)),
                ('stu_photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
