# Generated by Django 2.2.7 on 2020-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200325_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_status',
            field=models.BooleanField(default=False, verbose_name='Are You Married'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
