# Generated by Django 2.2.7 on 2020-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='per_address',
            field=models.TextField(default=None, max_length=555),
        ),
        migrations.AddField(
            model_name='person',
            name='per_photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='per_pincode',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='person',
            name='per_status',
            field=models.BooleanField(default=True, verbose_name='Are You Married'),
        ),
    ]
