# Generated by Django 2.2.7 on 2020-03-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200326_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='per_photo',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
